#!/bin/bash

# Depends:
# bin: bash cat cut sed(GNU) grep man groff
# debian: bash coreutils grep man-db groff-base

aeten_ads_init() {
	local args=${@}
	local input="$(cat -)"
	__aeten_ads_man_section name "${input}"

	echo eval "$(cat - << EOF

while [ \${#} -ne 0 ]; do
	case "\${1}" in
		$(aeten_ads_foreach_option  __aeten_ads_parse_option ${args})
		$(__aeten_ads_wrong_option)
	esac;
	shift;
done

EOF
)"
}

aeten_ads_foreach_option() {
	local lambda=${1}; shift
	local opt
	local name
	local short
	local value
	local description
	local prefix
	local options
	local options_plus_help
	local ifs_backup="${IFS}"
	while [ ${#} -ne 0 ]; do
		case "${1}" in
			-p|--prefix) prefix="${2}"; shift;;
		esac
		shift
	done

	IFS='
'
	options=$(echo "${input}"|sed '/^\s*#/d')
	options_plus_help="help: Print a help message.
${options}"
	for opt in ${options_plus_help}; do
		[ -z "${opt}" ] && continue
		eval "$(printf -- "${opt}"|sed 's/\(\!\)\{0,1\}\([a-zA-Z0-9-]\{1,\}\)\(|\([a-zA-Z0-9]\)\)\{0,1\}\(\s<\([a-zA-Z0-9-]\{1,\}\)>\)\{0,1\}:\s*\(.*\)/name=\2; short=\4; requiered=\1; value=\6; description="\7"/')"
		[ -z "${requiered}" ] && requiered=false || requiered=true
		[ -z "${short}" ] && short=$(echo ${name}|cut -c 1)
		eval "${lambda}"
	done
	IFS="${ifs_backup}"
}

aeten_ads_synopsys_usage() {
	printf ' [-%s|--%s <%s>]' ${short} ${name} "${value}"
}

aeten_ads_synopsys_man() {
	printf '.OP \-%s|--%s%s\n' ${short} ${name} "$([ -n "${value}" ] && echo " <${value}>")"
}

aeten_ads_help() {
	aeten_ads_groff|man -l -
}

aeten_ads_groff() {
	local input="$(cat /dev/stdin|sed 's/\\x0/\n/g')"
	for section in name version title short_description description; do
		__aeten_ads_man_section ${section} "${input}"
	done

	cat - << EOF
.TH $(echo $name|tr '[:lower:]' '[:upper:]') 1 "$(date +%D)" "$name ${version}" "${title}"
.ie \n(.g .ds Aq \(aq
.el		 .ds Aq '
.nh
.ad l
.SH NAME
.NH 1 ${name}
.PP
${name} - $(echo "${short_description}"|__aeten_ads_man_inline_style)
.SH SYNOPSYS
.
.SY ${name}
$(aeten_ads_foreach_option aeten_ads_synopsys_man)
.fi
.sp
.SH DESCRIPTION
$(echo "${description}"|__aeten_ads_man_inline_style)
.sp
.SH OPTIONS
$(aeten_ads_foreach_option __aeten_ads_man_opt)
EOF
}

aeten_ads_usage() {
	local input="$(cat /dev/stdin|sed 's/\\x0/\n/g')"
	local script=${1}
	shift
	local errno=${1}
	shift
	groff -T utf8 -man << EOF | sed '/^\s*$/d;/\s*()/d;/()\s*()/d' >/dev/fd/$([ "${errno}" -eq 0 ] && echo 1 || echo 2)
.TH
.SH Usage:
.SY $(basename ${script})
$(aeten_ads_foreach_option aeten_ads_synopsys_man)
EOF
	exit ${errno}
}

__aeten_ads_wrong_option() {
		echo "-*) $(readlink -f ${0}) usage ${name} 1 <<< '$(echo "${input}"|sed $"s/\$/\\\\x0/")'; exit 1;;"
}

__aeten_ads_man_section() {
	eval "${1}=\"$(echo "${2}"|sed --quiet "s/^\\s*#\\s*$(echo ${1}|tr '[:lower:]' '[:upper:]'):\\s*\\(.*\\)/\\1/p"|__aeten_ads_man_inline_style)\""
}

__aeten_ads_debug_option() {
	echo "$(${requiered} && echo '!')${name}|${short}$([ -z "${value}" ] || echo " <${value}>"): ${description}" >&2
}

__aeten_ads_parse_option() {
	local _varname=${prefix}$(echo ${name}|tr '[:lower:]' '[:upper:]'|tr - _)
	if [ help = "${name}" ]; then
		echo "-${short}|--${name}) $(readlink -f ${0}) help <<< '$(echo "${input}"|sed $"s/\$/\\\\x0/")'; exit 0;;"
	elif [ -z "${value}" ]; then
		echo "-${short}|--${name}) ${_varname}=true;;"
	else
		echo "-${short}|--${name}) [ -z "\$${_varname}" ] && ${_varname}=\${2} || ${_varname}+=\ \${2} ; shift;;"
	echo;
	fi
}

__aeten_ads_man_inline_style() {
	sed --regexp-extended 's/\\_/\\(ul/g; s/\\\*/\\[u0042]/g; s/([^\\])_([^_]+)_ ?/\n.I \1\2\n/g;s/([^\\])\*([^*]+)\* ?/\n.B \1\2\n/g ; s/\\\[u0042\]/*/g;'
}

__aeten_ads_man_opt() {
	cat - << EOF
.TP
.B \\-${short}
.TQ
.BI \\-\\-${name}\\  ${value}
$(echo "${description}"|__aeten_ads_man_inline_style)
EOF
}

__aeten_ads_api() {
	sed --quiet --regexp-extended 's/^aeten_ads_([[:alpha:]][[:alnum:]_-]+)\s*\(\)\s*\{/\1/p' "${*}" 2>/dev/null
}

__aeten_ads_is_api() {
	test 1 -eq $(__aeten_ads_api "${1}"|grep "^${2}$"|wc -l) 2>/dev/null
}

aeten_ads_cmd=${1}
if __aeten_ads_is_api ${0} ${aeten_ads_cmd}; then
   shift
   aeten_ads_${aeten_ads_cmd} "${@}"
   exit $?
# Allows script content inclusion
elif [ "$(basename $(readlink -f ${0}))" = 'aeten-ads' ]; then
   exit 1
fi

