#!/bin/bash
. <(ads init --prefix OPT_ -- $@ <<-ADS
#NAME: aneth-roff-style
#TITLE: Roff style generator user manual
#VERSION: 1.1
#RESUME: Aneth's roff document style generator.
#DESCRIPTION: TODO
#AUTHOR: Thomas Pérennou <thomas@aneth.dev>
#LICENCE: GLPv3
#COPYLEFT: Thomas Pérennou

?output /file: Output _file_ destination. The default is the name of executable with the appropriate extension in the current directory.

!name short-name: The document short name.
?title the-title: The document title.
?man-section: The manpages section number.

?cover-page: Creates a cover page page containing title, document reference, resume, authors, approbations.
?even-odd|O: Enable double-sided printing. Headers and footers for even and odd pages are formatted differently.
?banner-header|B: Highlights header with _primary color_.
?primary-color| rgb: Primary color. Can retrieved from _first-page-header_ with Image Magik's _covert_ command. See colors section below.
?secondary-color| rgb: Secondary color. See colors section below.
?first-page-header| /image: Image to use as header of the first page for PDF manual.
?left-header-logo| /logo: Logo to use at left header for PDF manual.
?right-header-logo| /logo: Logo to use at right header for PDF manual.
?center-header-logo| /logo: Logo to use at center header for PDF manual.
?style-section| style(none|highlight|underline): Defines the style of the titles of sections.
?style-subsection| style(none|highlight|underline): Defines the style of the titles of sections.

?reference ref: The document reference. If no given, will be _<name.version>_.
?project name: The project name.
?project-reference| ref: The project reference.
?redactor| name: Set redactor name.
?verifier| name: Set verifier name.
?approbator| name: Set approbator name.
?formalizer| name: Set formalizer name.
?acceptor| name: Set acceptor name.
?diffusion| level(intern|extern): The diffusion level.
?classification| level(normal|restricted|confidential|secret|confidential-defense|secret-defense): The classification level.

#COLORS: The format must be in hexadecimal RGB like `#A1234B`.
ADS
)

# {{{ stylesheet
__groff_pdf_stylesheet() {
	local _first_page_header_dimentions _first_page_header_height # cm
	cat <<-GROFF
		.nr PO 2c
		.nr IN 1c
		.nr LL 17c
		.nr LT 17c
		.nr PS 0.4c
		.nr PS-SS 0.4c
		.nr PS-SH 0.5c
		.nr VS 0.52c
		.nr SN 0.5c
		.fam H
		.
	GROFF
	__groff_pdf_stylesheet_colors
}

__pdf_height() { # return height (in cm) of the given PDF file. 0 if file not found
	local _dimentions
	local _pdf=$1
	if [[ -f $_pdf ]]; then
		_dimentions=$(pdfinfo "${_pdf}"| sed -n 's/Page *size: *\([[:digit:].]*\) *x *\([[:digit:].]*\).*$/\1x\2/p')
		awk 'BEGIN{print (21*'${_dimentions#*x}')/'${_dimentions%x*}' "c" }'
	else
		echo 0c
	fi
}

__groff_pdf_stylesheet_colors() {
	if [[ -n ${OPT_FIRST_PAGE_HEADER} ]]; then
		: ${OPT_PRIMARY_COLOR:=#$(convert ${OPT_FIRST_PAGE_HEADER} -flatten +dither -colors 2 -unique-colors -depth 8 -alpha off -format "%[hex:u]\\n" info:)}
	fi
	if ${OPT_BANNER_HEADER:-false}; then
		if __is_dark ${OPT_PRIMARY_COLOR#*#}; then
			cat <<-GROFF
				.defcolor banner-header-fg rgb #ffffff
				.defcolor banner-header-bg rgb ${OPT_PRIMARY_COLOR}
			GROFF
		else
			cat <<-GROFF
				.defcolor banner-header-fg rgb #000000
				.defcolor banner-header-bg rgb ${OPT_PRIMARY_COLOR}
			GROFF
		fi
	else
		if __is_dark ${OPT_PRIMARY_COLOR#*#}; then
			cat <<-GROFF
				.defcolor banner-header-fg rgb ${OPT_PRIMARY_COLOR}
				.defcolor banner-header-bg rgb #ffffff
			GROFF
		else
			cat <<-'GROFF'
				.defcolor banner-header-fg rgb #000000
				.defcolor banner-header-bg rgb #ffffff
			GROFF
		fi
	fi
	if [[ ${OPT_STYLE_SECTION} = highlight ]]; then
		if __is_dark ${OPT_PRIMARY_COLOR#*#}; then
			cat <<-GROFF
				.defcolor section-fg rgb #ffffff
				.defcolor section-bg rgb ${OPT_PRIMARY_COLOR}
			GROFF
		else
			cat <<-GROFF
				.defcolor section-fg rgb #000000
				.defcolor section-bg rgb ${OPT_PRIMARY_COLOR}
			GROFF
		fi
	else
		cat <<-GROFF
			.defcolor section-fg rgb ${OPT_PRIMARY_COLOR}
			.defcolor section-bg rgb #ffffff
		GROFF
	fi
	if [[ ${OPT_STYLE_SUBSECTION} = highlight ]]; then
		: ${OPT_SECONDARY_COLOR:=${OPT_PRIMARY_COLOR}}
		if __is_dark ${OPT_SECONDARY_COLOR#*#}; then
			cat <<-GROFF
				.defcolor subsection-fg rgb #ffffff
				.defcolor subsection-bg rgb ${OPT_SECONDARY_COLOR}
			GROFF
		else
			cat <<-GROFF
				.defcolor subsection-fg rgb #000000
				.defcolor subsection-bg rgb ${OPT_SECONDARY_COLOR}
			GROFF
		fi
	else
		cat <<-'GROFF'
			.defcolor subsection-fg rgb #000000
			.defcolor subsection-bg rgb #ffffff
		GROFF
	fi
}

__is_dark() {
	local _color=${*// /} # %02x%02x%02x r g b
	! (( ((299 * 16#${_color:0:2} + 587 * 16#${_color:2:2} + 114 * 16#${_color:4:2}) / (1000)) < 128 ))
}
# }}} stylesheet

# {{{ Macros
__groff_pdf_macros() {
	preconv <<-'GROFF'
		.make-symetric copyleft ©
		.
	GROFF
	cat <<-'GROFF'
		.de highlight-TH
			\h'-4c'\M[banner-header-bg]\D'P 0 (u;-\\n[.v]) 23c 0 0 (u;\\n[.v])'\h'-19c'\M[]
			.	sp (u;-(\\n[.v]/2+\\n[.s]))
		..
		.de box
			\[br]\*\[br]\l'|0\[rn]'\l'|0\[ul]'
		..
		.ds rotate "\X'ps: exec gsave currentpoint 2 copy translate \\$1 rotate neg exch neg exch translate'
		.ds restore "\X'ps: exec grestore'
		.
		.de make-symetric
		.	nr symetric \w'\\$2'
		.	char \\[\\$1] \
				\v'-\\\\n[rsb]u'\v'-\\\\n[rst]u'\
				\h'\w'\\$2'u'\X'ps: exec gsave currentpoint \
				2 copy translate -180 rotate neg exch neg exch \
				translate'\\$2\X'ps: exec grestore'\h'-\w'\\$2'u'\
				\v'\\\\n[rst]u'\v'\\\\n[rsb]u'
		.	rr symetric
		..
		.de aneth-pdfpic
			\X'pdf: pdfpic \\$*'
		..
	GROFF

	__groff_pdf_header
	__groff_pdf_footer
	__groff_pdf_sections
	if ${OPT_COVER_PAGE:-false}; then
		__groff_pdf_cover_page
	fi
}

__groff_pdf_sections() {
	case "${OPT_STYLE_SECTION}" in
		highlight)
			cat <<-'GROFF'
				.de highlight-SH
					\h'-4c'\M[section-bg]\D'P 0 (u;-\\n[.v]) 23c 0 0 (u;\\n[.v])'\h'-19c'\M[]
					.	sp (u;-((\\n[.v]/2)+(2*2*\\n[.s]u)))
				..
			GROFF
		;;
		underline)
			cat <<-'GROFF'
				.de highlight-SH
					\h'-4c'\M[section-bg]\D'P 0 (u;\\n[.v]-2p) 23c 0 0 (u;\\n[.v])'\h'-19c'\M[]
					.	sp (u;-(\\n[.v]/2+\\n[.s]))
				..
			GROFF
		;&
		*)
			cat <<-'GROFF'
				.de highlight-SH
				..
			GROFF
		;;
	esac
	cat <<-'GROFF'
		.rn SH SH-orig
		.de SH
		.	rs
		.	sp 1v
		.	vs (u;\n[PS-SH]*2)
		.	highlight-SH
		.	vs
		.	ns
		.	SH-orig \m[section-fg]\s[\n[PS-SH]u]\v[(u;-((v;\\n[.v]/2)+(2*\\n[.s]u)))u\\$*\s[\n[PS]u]\m[]
		.	set-an-margin
		.	nr IN 1c
		.	rs
		.	vs \\n[VS]u
		.	ll 17c
		.	if d aneth-style-section .sp 0.7v
		.	ns
		..
		.rn SS SS-orig
		.de SS
		.	rs
		.	sp 1v
		.	ps \n[PS-SS]u
		.	SS-orig \m[section-fg]\s[\n[PS-SS]u]\\$*\s[\n[PS]u]\m[]
		.	set-an-margin
		.	nr IN 1c
		.	ps \n[PS]u
		.	rs
		.	vs \\n[VS]u
		.	ll 17c
		.	sp 0.3v
		.	ns
		..
	GROFF
}
# }}} Macros

# {{{ Macros: hreader & footer
__groff_pdf_header() {
	cat - <<-GROFF
		.nr aneth-has-first-page-header $(( ${#OPT_FIRST_PAGE_HEADER} > 0 ))
		.nr aneth-first-page-header-height $(__pdf_height ${OPT_FIRST_PAGE_HEADER})
	GROFF
	cat - <<-'GROFF'
		.nr aneth-has-logo 0
		.if d aneth-left-header-logo .nr aneth-has-logo 1
		.if d aneth-center-header-logo .nr aneth-has-logo 1
		.if d aneth-right-header-logo .nr aneth-has-logo 1
		.
		.de aneth-logo
		.	ie \\n[aneth-has-logo] \{
		.		rs
		.		vs 0
		.		po 0.6c
		.		sp |0.5c
		.		if d aneth-left-header-logo .aneth-pdfpic \\*[aneth-left-header-logo] -L 0 0.6c
		.		if d aneth-center-header-logo .aneth-pdfpic \\*[aneth-center-header-logo] -C 0 0.6c 21c
		.		if d aneth-right-header-logo .aneth-pdfpic \\*[aneth-right-header-logo] -R 0 0.6c 20.4c
		.		sp
		.		po \n[PO]u
		.	\}
		..
		.de1 PT
		.	nr aneth-is-first-page (\\n[.pn]==2) \" First page. .pn has already been incremented.
		.	ie (\\n[aneth-is-first-page]) \{
		.		pdfinfo /Author \*[aneth-author] \*[aneth-authors]
		.		pdfinfo /Subject \*[aneth-name] - \*[aneth-resume]
		.		pdfinfo /Title \\*[an-extra3]
		.		pdfinfo /Keywords \*[aneth-name] \*[aneth-i18n-manual] \*[aneth-keywords]
		.		pdfinfo /Creator md2roff (with Aneth stylesheet)
		.		pdfinfo /Identifier \*[aneth-identifier]
		.		pdfinfo /Version \*[aneth-version]
		.		ie \n[aneth-has-first-page-header] \{
		.			rs
		.			po 0
		.			vs 0
		.			sp |0
		.			aneth-pdfpic \*[aneth-first-page-header] -L 21.05c
		.			sp 0
		.			vs
		.			po \n[PO]u
		.		\}
		.		el .aneth-logo
		.	\}
		.	el .aneth-logo
		.	fam \n[.fam]
		.	vs 0
		.	ps \n[PS-SH]
		.	nr margin \n[PS-SH]
		.	nr vertical-space (u;\n[PS-SH]+(2*\\n[margin]))
		.	vs \\n[vertical-space]u
		.	ie (\\n[aneth-is-first-page] & \n[aneth-has-first-page-header]) .sp |\n[PS-SH]u
		.	el \{
		.		sp |(1.6c)
		.		if '\*[aneth-banner-header]'true' .highlight-TH
		.	\}
		.	ns
		.	vs
		.	ps \n[PS]u
		.	ie '\*[aneth-banner-header]'true' \{
		.		ie (\\n[aneth-is-first-page] & \n[aneth-has-first-page-header]) \m[banner-header-fg]
		.		el \m[banner-header-fg]
		.	\}
		.	el \m[banner-header-fg]
		.	po 1c
		.	lt 19c
		.	ie d aneth-section .tl %\s[\\n[PS]u]\fB\\*[aneth-name]\fR(\\*[aneth-section])%\s[\\n[PS-SS]u]\fB\\*[an-extra3]\fR\s[\\n[PS]u]%\fB\\*[aneth-name]\fR(\\*[aneth-section])\fR\x'-\\n[margin]u'\x'(u;\\n[margin]*2)'%
		.	el                 .tl %\s[\\n[PS]u]\fB\\*[aneth-name]%\s[\n[PS-SH]u]\fB\\*[an-extra3]\fR\s[\\n[PS]u]%\fB\\*[aneth-name]\fR\x'-\\n[margin]u'\x'(u;\\n[margin]*2)'%
		.	\m[]
		.	ie (\\n[aneth-is-first-page] & \n[aneth-has-first-page-header]) \{
		.		sp |(u;(\n[aneth-first-page-header-height])+(2.5*(\\n[PS-SH])))
		.	\}
		.	po
		.	lt
		.	el .sp \\n[PS-SH]
		.	ns
		.
		..
	GROFF
}

__groff_pdf_footer() {
	cat <<-'GROFF'
		.rn BT BT-orig
		.de1 BT
		.	ds an-extra2 \*[aneth-name]
		.	BT-orig
		..
	GROFF
}
# }}} Macros: hreader & footer

# {{{ Macros: cover page
__groff_pdf_cover_page() {
	if ${OPT_COVER_PAGE:-false}; then
		cat <<-'GROFF'
			.\" TODO
		GROFF
	fi
}
# }}} Macros: cover page

if [[ -n ${OPT_OUTPUT} ]]; then
	exec 1>${OPT_OUTPUT}
fi

declare -p | sed -n 's/^declare \(-[-a-z]\+\)\? OPT_\(.*\)="\(.*\)"$/aneth-\2 \3/p' | awk '{gsub("_","-",$1); key=$1; $1=""; $1=$1;printf(".ds %s \"%s\n", tolower(key), substr($0,2))}' | preconv

__groff_pdf_stylesheet
__groff_pdf_macros

cat <<-'GROFF'
	.fam H
	.
GROFF
