#!/bin/sh

. $(dirname "$0")/../aeten-cli.sh

aesh() {
   local cmdline arg0
   while true; do
      printf '$ '
      read cmdline
      for arg in ${cmdline}; do
         arg0=${arg}
         break
      done
      __aeten_cli_is_api ${arg0} || cmdline="check --verbose -- ${cmdline}"
      ${cmdline}
   done
}

aesh "${@}"
